# Dockerfile - Desarrollo Backend (Go)
FROM golang:1.26.2-alpine

WORKDIR /app

RUN apk add --no-cache git

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# El servidor de Go corre en el 8080
EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
